<a href="https://colab.research.google.com/github/karina-munoz/Rep_phyton/blob/main/Tema11_NUMPY(m%C3%B3dulo).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Módulo NUMPY

In [1]:
#Se importa libreria numpy con el "apodo" np
import numpy as np
a = [1,2,3]
print(type(a))
#print(3 * a)
#print(a+a)
a = np.array(a) # Esta funcion permite manejar a "a" como un vector
print(type(a))
print(3 * a)
print(a+a)

<class 'list'>
<class 'numpy.ndarray'>
[3 6 9]
[2 4 6]


In [2]:
Diez = np.linspace(1,10,100)
#print(Diez)
Ceros = np.zeros(3)
print(Ceros)

[0. 0. 0.]


In [3]:
b = np.array([-1,-60,12,3.5,2,3,3])
Min = np.amin(b) # Obtengo el valor minimo del vector "b" 
print(Min)
Max = np.amax(b) # Obtengo el valor minimo del vector "b"
print(Max)
Donde_3_5 = np.where(b == 3.5) # Nos indica en que posicion del vector "b"  se cumple que sea igual a 3.5 
print(Donde_3_5)
Donde_3 = np.where(b == 3)
print(Donde_3)

-60.0
12.0
(array([3]),)
(array([5, 6]),)


In [4]:

#1X^2 - 3x + 2 = 0
Ecu_1 = np.array([1,-3,2]) 
Sol_1 = np.roots(Ecu_1)  # Esta funcion nos indica en que puntos una ecuacion toma el valor de 0, puede ser de grados mayores
print(Sol_1)
#4x^4 - 2x^2 + 3x - 2 = 0
Ecu_2 = np.array([4,0,-2,3,-2])
Sol_2 = np.roots(Ecu_2)
print(Sol_2)

[2. 1.]
[-1.20921113+0.j          0.26185021+0.73117971j  0.26185021-0.73117971j
  0.6855107 +0.j        ]


In [6]:
#5x - 3y - z = 1
#x + 4y -6z = -1
#2x + 3y + 4x = 9
X = np.array([[5,-3,-1],[1,4,-6],[2,3,4]])
Val = np.array([1,-1,9])
print(X)
print("------------")
print(Val)
print("------------")
Sol_S = np.linalg.solve(X,Val) #Nos permite resolver un sistema de ecuaciones, puede ser mayor a 3
print(Sol_S)

[[ 5 -3 -1]
 [ 1  4 -6]
 [ 2  3  4]]
------------
[ 1 -1  9]
------------
[1. 1. 1.]
